package exception;

public class MainException {

    public static void main(String[] args) {
//
//        int[] numbers = {1, 5, 4, 2, 9, 24, 23};
//try {
//    System.out.println("NUmber found: "+ isFoundNumber(numbers,10));
//
//
//        }catch (Num){
//    System.out.println("fdgbxdg");
//        }
//
//        public static boolean isFoundNumber(int[]number, int element){
//            for (int number:numbers){
//                if(number==element){
//                    return true;
//                }
//
//            }return false;
//        }
    }
}
